surfstudio/ReactiveDataDisplayManager

- Source/BaseTableDataDisplayManager.swift
- Source/Protocols.swift
This pull request contains fixes of SelectableItem and BaseTableDataDisplayManager to add deselect functionality
> Added functionality of deselect SelectableItem

- Source/BaseTableDataDisplayManager.swift
- Source/Event.swift
- Source/Protocols.swift
This pull request contains comments fixes.
This style is ok?
> Comments fixes

- ReactiveDataDisplayManager.xcodeproj/project.pbxproj
- Source/BaseTableDataDisplayManager.swift
- Source/HeaderableTableDataDisplayManager.swift
- Source/Protocols.swift
In this pull request I've added DDM for creating tables with multiple headers
> Headerable ddm

- Source/HeaderableTableDataDisplayManager.swift
Added scroll actions:
- after inserting new generators
- before removing generators
> Added scroll actions

- ReactiveDataDisplayManager.xcodeproj/project.pbxproj
- Source/BaseTableDataDisplayManager.swift
- Source/Protocols.swift
- Removed didSelected property from SelectableItem
- Fixed Info.plist warning
- Fixed some comments
> Little improvements

- Source/BaseTableDataDisplayManager.swift
- Source/Event.swift
- Source/Extensions.swift
- Source/HeaderableTableDataDisplayManager.swift
- Source/Protocols.swift
- Added functionality for add after
> Improvements

- Example/ReactiveDataDisplayManager/Collection/TitleCollectionGenerator.swift
- Example/ReactiveDataDisplayManager/Table/TitleTableGenerator.swift
- Source/Protocols.swift
- Added default implementations for TableCellGenerator and CollectionCellGenerator generate methods
- Fixed Example project (removed generate method call)
> Generator improvements

- Example/ReactiveDataDisplayManager/Collection/CollectionViewController.swift
- Example/ReactiveDataDisplayManager/Table/TableViewController.swift
- Source/Event.swift
- Added optional listeners adding
- Fixed example project
> Event improvements

- Source/HeaderableTableDataDisplayManager.swift
- Fixed section removing when remove last generator from section
> Headerable ddm fixes

- Source/HeaderableTableDataDisplayManager.swift
- Fixed crash with empty sections
> Headerable ddm crash fix

- Source/BaseCollectionDataDisplayManager.swift
> BaseCollectionDataDisplayManager access level fixed

- Source/HeaderableTableDataDisplayManager.swift
- Make generators visible.
- Make classes open.
- Add update generators function.
> Extension for HeaderableTableDataDisplayManager

- Source/HeaderableTableDataDisplayManager.swift
- Change access modifier to open at willdisplaycell.
> Change access modifier to open at willdisplaycell.

- .codecov.yml
- .travis.yml
- README.md
- ReactiveDataDisplayManager.xcodeproj/xcshareddata/xcschemes/ReactiveDataDisplayManager.xcscheme
- ReactiveDataDisplayManagerTests/BaseTableDataDisplayManagerTests.swift
- Added test running and results uploading to codecov in travis
- Added shared scheme
> Codecov setup

- .codecov.yml
- .travis.yml
- Fixed build script to correct coverage handling (now we can see our code coverage in codecov)
> Coverage fixes

- README.md
- ReactiveDataDisplayManager.podspec
- ReactiveDataDisplayManagerTests/BaseTableDataDisplayManagerTests.swift
- Source/BaseCollectionDataDisplayManager/BaseCollectionDataDisplayManager.swift
- Source/BaseTableDataDisplayManager/BaseTableDataDisplayManager.swift
- Source/Protocols.swift
This issue also have discussed at #40
> Moved register cell from RDDM to generator

- .travis.yml
- README.md
- ReactiveDataDisplayManager.podspec
- ReactiveDataDisplayManager.xcodeproj/project.pbxproj
- ReactiveDataDisplayManagerTests/BaseTableDataDisplayManagerTests.swift
- Source/BaseTableDataDisplayManager/BaseTableDataDisplayManager.swift
- Source/BaseTableDataDisplayManager/ExtendableBaseTableDataDisplayManager.swift
- Source/BaseTableDataDisplayManager/PaginableBaseTableDataDisplayManager.swift
Converted RDDM to Swift 4.2.
According to #35 issue, created method `reloadSection(by sectionHeaderGenerator)` and added tests for it
> Moving to swift 4.2, Adding reload section method

- ReactiveDataDisplayManager.podspec
- Source/BaseTableDataDisplayManager/BaseTableDataDisplayManager.swift
- Source/BaseTableDataDisplayManager/PaginableBaseTableDataDisplayManager.swift
- Source/Protocols.swift
Issue #47 done - add ability to move generators. Bug #46 fixed - PaginableTableManager works improperly.
> Solve issue and fix bug

- ReactiveDataDisplayManager.xcodeproj/project.pbxproj
- Source/BaseTableDataDisplayManager/GravityTableDataDisplayManager.swift
- Source/BaseTableDataDisplayManager/Support/EmptyGravityTableHeaderGenerator.swift
- Source/Protocols.swift
Uses for sorting cells and headers based on heaviness property.
> Add GravityTableDataDisplayManager

- README.md
- ReactiveDataDisplayManager.podspec
- ReactiveDataDisplayManagerTests/BaseTableDataDisplayManagerTests.swift
- Source/BaseCollectionDataDisplayManager/BaseCollectionDataDisplayManager.swift
- Source/BaseStackDataDisplayManager/BaseStackDataDisplayManager.swift
- Source/BaseTableDataDisplayManager/BaseTableDataDisplayManager.swift
- Source/BaseTableDataDisplayManager/GravityTableDataDisplayManager.swift
- Source/BaseTableDataDisplayManager/PaginableBaseTableDataDisplayManager.swift
- Source/DataDisplayManager.swift
- Source/Protocols.swift
Add completion on end reload data.
```swift
adapter?.forceRefill {
// some code after reload ends
}
```
> Add forceRefill completion

- Source/BaseTableDataDisplayManager/BaseTableDataDisplayManager.swift
- Source/BaseTableDataDisplayManager/PaginableBaseTableDataDisplayManager.swift
- Source/Protocols.swift
- Source/Utils/Extensions.swift
Небольшие доработки для **BaseTableDataDisplayManager**, позволившие реализовать пару фич. 
- Для `BaseTableDataDisplayManager` добавлена обработка событий _willDisplayCellEvent_ и _didEndDisplayCellEvent_
- Добавлен протокол `DisplayableFlow` - который позволяет для _TableCellGenerator_ и _TableHeaderGenerator_ обрабатывать события willDisplayEvent и didEndDisplayEvent. (В проекте на этой базе реализована поддержка прочтения сообщений. Альтернатива общему эвенту)
- Для `BaseTableDataDisplayManager ` добавлены методы скролла до _TableCellGenerator_ и _TableHeaderGenerator_ с различными параметрами. 
- Добавлены методы для пакетных вставок генераторов, а так же новой секции с новым headGenerator. 
- Небольшой рефакторинг, в связи с варнингами от линтера. 
В реализации `tableView(_ …
> Batch inserts

- ReactiveDataDisplayManager.xcodeproj/project.pbxproj
- ReactiveDataDisplayManagerTests/FoldingTableDataDisplayManagerTests.swift
- ReactiveDataDisplayManagerTests/GravityFoldingHeaderGenerator.swift
- Source/BaseTableDataDisplayManager/FoldingTableDataDisplayManager.swift
- Source/BaseTableDataDisplayManager/GravityFoldingTableDataDisplayManager.swift
- Source/BaseTableDataDisplayManager/GravityTableDataDisplayManager.swift
- Source/Protocols.swift
Uses for expand and collapse cells.
> Add folding extensions to BaseDDM and GravityDDM.

- ReactiveDataDisplayManagerTests/BaseCollectionDataDisplayManagerTests.swift
- ReactiveDataDisplayManagerTests/FoldingTableDataDisplayManagerTests.swift
- ReactiveDataDisplayManagerTests/GravityFoldingHeaderGenerator.swift
> #74 fix tests

- Example/ReactiveDataDisplayManager/Base.lproj/Main.storyboard
- Example/ReactiveDataDisplayManager/Collection/ImageCollectionViewController/Cells/ImageCell/ImageCollectionViewCell.swift
- Example/ReactiveDataDisplayManager/Collection/ImageCollectionViewController/Cells/ImageCell/ImageCollectionViewCell.xib
- Example/ReactiveDataDisplayManager/Collection/ImageCollectionViewController/ImageCollectionViewController.swift
- Example/ReactiveDataDisplayManager/Collection/MainCollectionViewController/MainCollectionViewController.swift
- Example/ReactiveDataDisplayManagerExample.xcodeproj/project.pbxproj
- ReactiveDataDisplayManager.xcodeproj/project.pbxproj
- Source/REFACTORING/Collection/Collection+RDDM.swift
- Source/REFACTORING/Collection/DataSource/BaseCollectionDataSource.swift
- Source/REFACTORING/Collection/Delegate/BaseCollectionDelegate.swift
- Source/REFACTORING/Collection/Events/CollectionEvent.swift
- Source/REFACTORING/Collection/Manager/BaseCollectionManager.swift
- Source/REFACTORING/Collection/Plugins/BaseCollectionPlugin.swift
- Добавлена реализация RDDM для CollectionView (Events, Plagins, DataSource, Delegate)
- Добавлены базовые события CollectionView
- Добавлен базовый пример конфигурации CollectionView с новым подходом. Называется "Gallery without prefetching".
Обновление архитекруты RDDM для CollectionView
- Экран с примером работы называется "Gallery without prefetching", возможно стоило бы назвать его по другому, так как цель экран, это показ базовую настройку, а не загурзку картинок.  
- Возможно, стоит добавить показ Header для секции,  или все же отложить эту идею до след. прмером, а этот оставить максимально простым.
- Открыть таб "Collection"
- Выбрать "Gallery without prefetching"
> Add new base approach for collection view

- Example/ReactiveDataDisplayManager/Base.lproj/Main.storyboard
- Example/ReactiveDataDisplayManager/Collection/MainCollectionViewController/MainCollectionViewController.swift
- Example/ReactiveDataDisplayManager/Collection/SizableCollectionViewController/Cells/SizableCell/SizableCollectionViewCell.swift
- Example/ReactiveDataDisplayManager/Collection/SizableCollectionViewController/Cells/SizableCell/SizableCollectionViewCell.xib
- Example/ReactiveDataDisplayManager/Collection/SizableCollectionViewController/Generators/SizableGenerator/VerticalSizableTextGenerator.swift
- Example/ReactiveDataDisplayManager/Collection/SizableCollectionViewController/SizableCollectionViewController.swift
- Example/ReactiveDataDisplayManagerExample.xcodeproj/project.pbxproj
- ReactiveDataDisplayManager.xcodeproj/project.pbxproj
- Source/REFACTORING/Collection/Collection+RDDM.swift
- Source/REFACTORING/Collection/Delegate/BaseCollectionDelegate.swift
- Source/REFACTORING/Collection/Delegate/FlowCollectionDelegate.swift
- Дабавлена поддержка SizableCollectionCellGenerator из старой версии RDDM.
- Добавлен пример использования. Называется "Sizable collection". (Пример основан на вертикальном скролле, и показывает как ячейка с текстом может вытягиваться по высоте, в зависимости от длины текста.)
Одной из проблем использвоания RDDM было расширение базового менеджера, для возможности рассчета размера ячейки. 
Проекты на котрых ссылался при работе: 
- РивГош
- Триколор
- Бетховен 
1)  Сам по себе SizableCollectionCellGenerator бесполезен без контекста работы layout, и вообще общей задумки. 
Метод Flow делегата вызывает только UICollectionViewFlowLayout, и не  никакой гарантии что кастомный Layout будет использовать эти методы. 
Отсюда получается, что SizableCollectionCellGenerator будет работать 100% только с …
> Add sizable cell support

- .github/workflows/Build.yml
- Добавлены триггеры для GitHubActions на push
- ...
Чтобы пофиксить отсутствие покрытия на ветке develop и чтобы актуализировать эти репорты.
- ...
- Посмотреть в Actions вкладке репозитория
> add triggers on push
